Product:
    type: object
    inherits:
        - 'ProductDecorator'
    config:
        description: "Represents your product"
        fields:
            catnum:
                type: String
                description: Catalog number
