Product:
    type: object
    config:
        description: "Represents a product"
        fields:
            id:
                type: "ID!"
                description: "Internal identifier"
            name:
                type: "String"
                description: "Localized product name (domain dependent)"
            partno:
                type: "String"
                description: "Product Part Number"
            ean:
                type: "String"
                description: "Product EAN code"
