MutationDecorator:
    type: object
    decorator: true
    config:
        fields:
            Product:
                type: Product!
                resolve: "@=mutation('create_product', [args])"
                args:
                    input:
                        type: ProductInput!
